# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ta_tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low', models.CharField(max_length=25)),
                ('high', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('scale_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=6, null=True)),
                ('ans1', models.CharField(max_length=250)),
                ('ans2', models.CharField(max_length=250)),
                ('ans3', models.CharField(max_length=250)),
                ('ans4', models.CharField(max_length=250)),
                ('ans5', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('date_completed', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=150, null=True)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ta_tutor.Tutor')),
            ],
        ),
    ]
