# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc123', models.CharField(max_length=6)),
                ('whole_name', models.CharField(max_length=30, null=True)),
                ('chair', models.CharField(max_length=12)),
                ('className', models.CharField(max_length=40, null=True)),
                ('classID', models.CharField(max_length=8)),
                ('question', models.CharField(max_length=100, null=True)),
                ('inSession', models.BooleanField(default=False)),
                ('host', models.CharField(max_length=150, null=True)),
                ('port', models.IntegerField(default=0)),
                ('isChat', models.BooleanField(default=0)),
                ('chat_token', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('abc123', models.CharField(max_length=6)),
                ('token', models.CharField(max_length=100, null=True)),
                ('forum_flag_count', models.IntegerField(default=0)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
